name: simple_reminder
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  eva_icons_flutter: ^3.0.0
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
